### ISSUE TITLE
Won't launch on Windows 10

### ISSUE THREAD

**Issue by cgwers** [PnRSolutions/bookerei-public#1]
Hi Jeff (it's "JustAnother"),

I finally had time to install the version from your first email and have the Won't Start issue. The updated email link also has that issue.

1.2.2 and 1.3.0 won't launch a GUI for me and I don't see a process in ProcExp64.
Here's my system info:

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
System Manufacturer	LENOVO
System Model	81FV
System Type	x64-based PC
System SKU	LENOVO_MT_81FV_BU_idea_FM_Legion Y530-15ICH
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2208 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	LENOVO 8JCN56WW, 11/30/2020
SMBIOS Version	3.0
Embedded Controller Version	1.56
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Product	LNVNB161216
BaseBoard Version	SDK0R32862 WIN
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume3
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	9.04 GB
Total Virtual Memory	23.6 GB
Available Virtual Memory	13.6 GB
Page File Space	7.75 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by d3lboy** [comment]
Hi, 

can you check if you have installed WindowsAppRuntime 1.5? Usually, Windows Store takes care about these prerequisites  and updates if needed.
If you need to install it, you can get it from [https://github.com/PnRSolutions/bookerei-public/releases/download/v1.3.0/Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe.Msix](https://github.com/PnRSolutions/bookerei-public/releases/download/v1.3.0/Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe.Msix)

**Comment by d3lboy** [comment]
@cgwers do you still have a problem? If not, I am going to close this issue.
