### ISSUE TITLE
The state of CopyExistingData switch button is not being saved

### ISSUE THREAD

**Issue by isannn** [PnRSolutions/bookerei-public#2]
I changed repo path from default to custom and trying to switch off the switch button "copy existing data" in order not to copy ebooks into storage bc do not have enough disk space. When I go to another screen, for example Home and then go back the setting is still switched on.
![image](https://github.com/user-attachments/assets/ecc5e4d7-0a3d-4967-b598-69d0ad3364f4)

**Comment by d3lboy** [comment]
Hi @isannn 

I see the issue, thanks.

I have planned a new release in the next few days, and since fixing this will not take much time, I will include it.

Best regards

**Comment by d3lboy** [comment]
Fixed in v1.5.1
