### ISSUE TITLE
Subshelves please

### ISSUE THREAD

**Issue by rcwombat** [PnRSolutions/bookerei-public#3]
Really need the ability to sub-categorise. Shelves are good, but if a Shelf can also be a Shelf of another that would greatly assist in organising...

**Comment by d3lboy** [comment]
Thank you for the suggestion.
It should be implemented in one of the upcoming releases.

**Comment by rcwombat** [comment]
Thanks, sounds promising. Love the simplicity, look and fell of the application as it is, and sub-shelves will make it much more useable!

**Comment by d3lboy** [comment]
@rcwombat 

Released version 1.6.0, which introduces the sub-shelves feature. You can now create parent and child shelf relationships (unlimited depth).

**Comment by rcwombat** [comment]
You're a legend! Thanks!!!
